### ISSUE TITLE
Question about interacting dapp - Wallet Connect

### ISSUE THREAD

**Issue by DiMiTriFrog** [bitlogik/pyWeb3#2]
I'm  trying to simulate a wallet like metamask but with python through wallet connect, but I can't find a way to connect through wallet connect to the dapp and verify the wallet.

To do this I should first set up a wallet with private key and configured to the chain I want to connect, then use that private key to sign the messages, correct?

But I can't find how with the messages that the walletconnect returns I can verify the message.

Does anyone know of an example on which I can base?

I would like  something like a Metamask in python scripting.

**Comment by bitlogik** [comment]
You can base your work on Uniblow. It is a full blockchain wallet, doing like Metamask for EVM chains, and it uses pyWalletConnect and pyWeb3 under the hood.

The core file for the "EVM" wallet is _wallets/ETHwallet.py_. And for WalletConenct message processing it is there : https://github.com/bitlogik/uniblow/blob/master/wallets/ETHwallet.py#L448

I think you can use the code base as it is, using the internal API. First you need to instantiate a device, then a blockchain wallet. The wallet will handle WC, RPC, device connection,... For example something like (no guarantee it runs, just to provide an idea).

```
from device.SingleKey import SKdevice
# Change the right class, for example it can be BSC_wallet in BSCwallet
from wallets.ETHwallet import ETH_wallet


def watcher_fct():
    app.wallet.get_messages()

device = SKdevice()
# Private key
device.open_account_fromint(0x12345678zzzz)
app.device.set_key_type("K1")
# Here 2 means WalletConnect option
wallet = ETH_wallet(0, 2, device, wc_uri="wc:urifromwc", confirm_callback=thecb)
# Get address
print(wallet.get_account())
# Start a timer to call a watcher_fct
timer = aTimer()
timer.Notify = watcher_fct
```

You would have some callbacks to manage the return and forth, as this is designed for an async GUI, but this can be faked to be standalone. Check what does confirm_callback in the code. This callback basically display the message to the user to confirm and return True or False depending of the user choice (accept or reject). So a simple "return True" will blindly accept all the signature requests.

A different alternative would be tu use Web3py, but I think it is not compatible with WalletConnect, maybe in pair with pyWalletConnect.

Additionally to all these free GPL code related (pyWeb3, pyWalletConnect and Uniblow), we also developed an in-house proprietary Python code for a programmatic EVM wallet. The wallet "signer" part is included, with RPC and everything. This is designed for DeFi bot applications, and refactored for speed (0.07 ms to generate a transaction and sign it). This is easy to use for building and broadcasting some transactions. You can contact us to contact@bitlogik.fr if your interested to acquire a license, and we can share the documentation.

**Comment by DiMiTriFrog** [comment]
Really worked, thank you very much.

I dont understand why people uses web3py instead of pyweb3, this library its more useful.
